# Prometheus configuration for Cloudless monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'cloudless-local'
    monitor: 'cloudless-monitor'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Scrape configurations
scrape_configs:
  # Coordinator metrics
  - job_name: 'coordinator'
    static_configs:
      - targets: ['coordinator:9090']
        labels:
          service: 'coordinator'

  # Agent metrics (would be dynamically discovered in production)
  - job_name: 'agents'
    static_configs:
      - targets:
          - 'agent-1:8090'
          - 'agent-2:8090'
          - 'agent-3:8090'
        labels:
          service: 'agent'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
